### ISSUE TITLE
Cam Normalization 

### ISSUE THREAD

**Issue by jaklevab** [eclique/keras-gradcam#4]
Hi there, very nice repository. Quick question, why are you normalizing the class activation maps when generating them in batches? 
https://github.com/eclique/keras-gradcam/blob/02d395ff20f74c4ea2bb69d82f1aadd065eb3abc/grad_cam.py#L133

Is it a way to enhance the class localization ? If so, why is this not done when generating them individually (without batches)

Thanks !

**Comment by eclique** [comment]
Hello. Hmmm, good question. I don't quite remember what is it doing there. I might have been trying different normalizations to enhance the saliency map. Computing `cams = np.einsum(..)` should be equivalent to computing `cam = np.dot(..)` in case of a single image. Post-processing after that is pretty flexible and can be changed.

**Comment by jaklevab** [comment]
Ok great ! Just wanted to make sure that the l2-normalization wasn't affecting any important step in the computation of the maps
